import {it,expect,vi} from 'vitest';
import type {SupabaseClient} from '@supabase/supabase-js';
import {SupabaseGateway,validateRemote} from '../src/cloud/gateway';
import {createGame} from '../src/simulation';
const owner='00000000-0000-4000-8000-000000000001';
const signal=new AbortController().signal;
function setup(data:unknown,error:unknown=null,user=owner){const reply={data,error};const chain:any={select:()=>chain,eq:()=>chain,abortSignal:()=>chain,maybeSingle:async()=>reply,then:(resolve:any)=>Promise.resolve(reply).then(resolve)};const client={auth:{getSession:async()=>({data:{session:{user:{id:user}}},error:null})},from:vi.fn(()=>chain),rpc:vi.fn(()=>chain)};return {client,gateway:new SupabaseGateway(client as unknown as SupabaseClient)};}
it('distinguishes a confirmed absent save from a malformed empty response',async()=>{expect(await setup(null).gateway.read(owner,signal)).toBeNull();await expect(setup(undefined).gateway.read(owner,signal)).rejects.toMatchObject({kind:'invalid'});});
it('refuses reads and commits when the SDK session belongs to another owner',async()=>{const s=setup(null,null,'other');await expect(s.gateway.read(owner,signal)).rejects.toMatchObject({kind:'auth'});expect(s.client.from).not.toHaveBeenCalled();});
it('does not treat failed remote reads as a new account',async()=>{await expect(setup(null,{status:401}).gateway.read(owner,signal)).rejects.toMatchObject({kind:'auth'});await expect(setup(null,{message:'network'}).gateway.read(owner,signal)).rejects.toMatchObject({kind:'network'});});
it('quarantines another owner, future formats, unsafe revisions and invalid reward states',()=>{const valid={owner_id:owner,state:createGame(1000000),format:4,revision:1,saved_at:new Date().toISOString(),operation_id:'operation'};expect(validateRemote(valid,owner).state.hearts).toBe(valid.state.hearts);for(const invalid of [{...valid,owner_id:'other'},{...valid,format:5},{...valid,revision:Infinity},{...valid,state:{...valid.state,hearts:-1}},{...valid,state:{...valid.state,missions:{}}}])expect(()=>validateRemote(invalid,owner)).toThrow();});
it('requires the intended operation, owner, next revision and server date in the acknowledgement',async()=>{const request={owner,expected:1,operation:'op',state:createGame(1000000),reason:'sync' as const,checkpoints:[]};await expect(setup({status:'ok',owner_id:owner,revision:3,operation_id:'op',saved_at:new Date().toISOString()}).gateway.commit(request,signal)).rejects.toMatchObject({kind:'invalid'});expect(await setup({status:'ok',owner_id:owner,revision:2,operation_id:'op',saved_at:new Date().toISOString()}).gateway.commit(request,signal)).toMatchObject({status:'ok'});});
