// @vitest-environment happy-dom
import {beforeEach,afterEach,it,expect,vi} from 'vitest';
import {GameController} from '../src/application/GameController';
import {sessionPolicy} from '../src/config/runtime';
import {mountAccountPanel,authMessage} from '../src/cloud/accountPanel';
const mocks=vi.hoisted(()=>({create:vi.fn(),send:vi.fn(),verify:vi.fn(),signout:vi.fn(),event:null as null|((event:string,session:unknown)=>void)}));
vi.mock('@supabase/supabase-js',()=>({createClient:mocks.create}));
const disposals:(()=>void)[]=[];
beforeEach(()=>{document.body.innerHTML='<section id="account-content" hidden></section>';localStorage.clear();mocks.create.mockReset();mocks.send.mockReset();mocks.verify.mockReset();mocks.signout.mockReset();mocks.event=null;mocks.create.mockReturnValue({auth:{signInWithOtp:mocks.send,verifyOtp:mocks.verify,signOut:mocks.signout,stopAutoRefresh:vi.fn(),startAutoRefresh:vi.fn(),onAuthStateChange:(fn:any)=>{mocks.event=fn;return {data:{subscription:{unsubscribe:vi.fn()}}};}}});});
afterEach(()=>{disposals.splice(0).forEach(fn=>fn());});
async function mount(config:{url:string;key:string}|null={url:'https://test.supabase.co',key:'sb_publishable_test'}){const c=new GameController({getItem:k=>localStorage.getItem(k),setItem:(k,v)=>localStorage.setItem(k,v)});disposals.push(()=>c.dispose());const dispose=await mountAccountPanel(c,{getItem:k=>localStorage.getItem(k),setItem:(k,v)=>localStorage.setItem(k,v)},sessionPolicy(false),()=>{},config);disposals.push(dispose);return c;}
const settle=async()=>{await Promise.resolve();await Promise.resolve();await Promise.resolve();};
it('keeps guest play honest when no managed project is configured',async()=>{const c=await mount(null);expect(mocks.create).not.toHaveBeenCalled();expect(document.body.textContent).toContain('ne sont pas disponibles');expect(c.getSnapshot().state!.rabbits).toHaveLength(2);});
it('never constructs an account SDK in the laboratory',async()=>{const c=new GameController({scope:'laboratory',getItem:()=>null,setItem:()=>{}});disposals.push(()=>c.dispose());await mountAccountPanel(c,{getItem:()=>null,setItem:()=>{}},sessionPolicy(true),()=>{}, {url:'https://test.supabase.co',key:'sb_publishable_test'});expect(mocks.create).not.toHaveBeenCalled();expect(document.querySelector('#account-content')!.hasAttribute('hidden')).toBe(true);});
it('requests email OTP and verifies the sent address with the provider',async()=>{await mount();mocks.send.mockResolvedValue({error:null});mocks.verify.mockResolvedValue({error:null});const email=document.querySelector<HTMLInputElement>('#account-email')!;email.value='tester@example.test';document.querySelector('form')!.dispatchEvent(new Event('submit',{cancelable:true}));await settle();expect(mocks.send).toHaveBeenCalledWith({email:'tester@example.test',options:{shouldCreateUser:true,emailRedirectTo:location.origin+location.pathname}});document.querySelector<HTMLInputElement>('#account-code')!.value='123456';document.querySelector<HTMLButtonElement>('#account-verify')!.click();await settle();expect(mocks.verify).toHaveBeenCalledWith({email:'tester@example.test',token:'123456',type:'email'});});
it('recovers controls after thrown network failures or an initial session event during OTP request',async()=>{await mount();let reject!:(error:Error)=>void;mocks.send.mockReturnValue(new Promise((_,r)=>{reject=r;}));document.querySelector<HTMLInputElement>('#account-email')!.value='tester@example.test';document.querySelector('form')!.dispatchEvent(new Event('submit',{cancelable:true}));mocks.event!('INITIAL_SESSION',null);await settle();reject(new Error('network'));await settle();expect(document.querySelector<HTMLButtonElement>('#account-send')!.disabled).toBe(false);mocks.send.mockResolvedValue({error:{status:429}});document.querySelector('form')!.dispatchEvent(new Event('submit',{cancelable:true}));await settle();expect(document.querySelector('#account-notice')!.textContent).toContain('Trop de demandes');});
it('explains invalid/expired codes, email quotas and unauthorized recipient restrictions',()=>{expect(authMessage({code:'otp_expired'})).toContain('expiré');expect(authMessage({status:429})).toContain('Attendez');expect(authMessage({code:'email_address_not_authorized'})).toContain('pas encore autorisée');});

it('enables official SDK handling of default email links without copying the guest automatically',async()=>{await mount();expect(mocks.create.mock.calls[0][2].auth.detectSessionInUrl).toBe(true);expect(document.querySelector('#account-send')!.textContent).toContain('e-mail');expect(document.querySelector('#account-choices')!.children).toHaveLength(0);});
