import {describe,it,expect} from 'vitest';
import {act,createGame,decodeGame,encodeGame} from '../src/simulation';
import {PARCEL_IDS,acquiredCell} from '../src/config/land';
import {DECORATION_IDS,DECORATIONS} from '../src/config/decorations';
import {footprint} from '../src/simulation/decorations';
import {GameController} from '../src/application/GameController';
import {SAVE_KEY,LAND_MIGRATION_BACKUP_KEY} from '../src/persistence/storage';
import type {Command,GameState} from '../src/state/types';
const run=(s:GameState,c:Command)=>{const r=act(s,c,0);if(!r.ok)throw Error(r.reason);return r.state};
const rich=()=>({...createGame(0),pattes:50000});
const buy=(s:GameState,id:Command & {type:'expand'})=>run(s,id);
function oldSave(extensions=0){const {acquiredParcels:_land,...s}=createGame(0);return {...s,version:5,expanded:extensions>0,secondExpanded:extensions>1,buildings:s.buildings.map(b=>({...b,x:0,y:0})),decorations:[] as Record<string,unknown>[]};}
describe('nine parcels and outside decorations v6',()=>{
 it('starts only at the centre with unchanged resources, rabbits and habitat proportions',()=>{const s=createGame(0);expect(s.version).toBe(7);expect(s.acquiredParcels).toEqual(['center']);expect(s.buildings[0]).toMatchObject({x:16,y:16});expect([s.pattes,s.grass,s.hearts,s.rabbits.length]).toEqual([300,10,12,2]);expect(acquiredCell(s,3,3)).toBe(true);expect(acquiredCell(s,2,3)).toBe(false)});
 it.each([{order:PARCEL_IDS.slice(1)},{order:PARCEL_IDS.slice(1).reverse()},{order:['southeast','northwest','south','east','north','west','northeast','southwest'] as const}])('buys all eight independently in order %j',({order})=>{let s=rich();const buildings=structuredClone(s.buildings);order.forEach((parcelId,i)=>{const before=s.pattes,expectedCost=(i+1)*500;s=buy(s,{type:'expand',parcelId,expectedCost});expect(s.pattes).toBe(before-expectedCost);expect(s.acquiredParcels.length).toBe(i+2);expect(s.buildings).toEqual(buildings)});expect(s.pattes).toBe(32000);expect(s.acquiredParcels.length).toBe(9);for(let y=0;y<9;y++)for(let x=0;x<9;x++)expect(acquiredCell(s,x,y)).toBe(true)});
 it('requires the confirmed current price, refuses duplicate purchases and does not unlock an intermediate parcel',()=>{let s=rich();const c:Command={type:'expand',parcelId:'northwest',expectedCost:500};s=run(s,c);expect(s.acquiredParcels).toEqual(['center','northwest']);expect(act(s,c,0)).toMatchObject({ok:false,state:s,reason:'ALREADY_EXPANDED'});expect(act(s,{type:'expand',parcelId:'south',expectedCost:500},0)).toMatchObject({ok:false,state:s,reason:'PRICE_CHANGED'});expect(act(createGame(0),c,0)).toMatchObject({ok:false,reason:'NOT_ENOUGH_PATTES'});expect(act(s,{type:'buyBuilding',kind:'farm',x:4,y:16},0)).toMatchObject({ok:false,reason:'INVALID_CELL'})});
 it('uses the existing hearts complement and credits no new reward twice',()=>{const s=createGame(0);s.pattes=475;const r=act(s,{type:'payWithHearts',action:{type:'expand',parcelId:'southeast',expectedCost:500},maxPattes:475,maxHearts:1},0);expect(r.ok).toBe(true);if(!r.ok)return;expect(r.state.hearts).toBe(11);expect(r.state.pattes).toBe(0);expect(r.state.missions.completed).toContain('bigger-meadow');expect(act(r.state,{type:'expand',parcelId:'southeast',expectedCost:500},0).ok).toBe(false)});
 it.each(DECORATION_IDS)('places, moves, stores and sells %s only outside buildings',catalogId=>{let s=run(rich(),{type:'buyDecoration',catalogId});const id=s.decorations[0].id;expect(act(s,{type:'placeDecoration',id,location:{kind:'habitat',habitatId:'building-1',slot:0} as unknown as import('../src/state/types').DecorationLocation},0)).toMatchObject({ok:false,reason:'INVALID_CHOICE'});expect(act(s,{type:'placeDecoration',id,location:{kind:'outside',x:16,y:16,rotation:0}},0)).toMatchObject({ok:false,reason:'CELL_OCCUPIED'});s=run(s,{type:'placeDecoration',id,location:{kind:'outside',x:12,y:12,rotation:0}});expect(act(s,{type:'buyBuilding',kind:'farm',x:12,y:12},0)).toMatchObject({ok:false,reason:'DECORATION_BLOCKS_BUILDING'});s=run(s,{type:'placeDecoration',id,location:{kind:'outside',x:20,y:20,rotation:0}});s=run(s,{type:'placeDecoration',id,location:{kind:'inventory'}});const before=s.pattes;s=run(s,{type:'sellDecoration',id});expect(s.pattes).toBe(before+Math.floor(DECORATIONS[catalogId].price*.5));expect(s.decorations).toEqual([]);expect(act(s,{type:'sellDecoration',id},0).ok).toBe(false)});
 it('rotates the tunnel and validates its complete footprint over acquired boundaries',()=>{let s=run(rich(),{type:'buyDecoration',catalogId:'play-tunnel'});expect(footprint('play-tunnel')).toEqual({width:2,height:1});expect(footprint('play-tunnel',1)).toEqual({width:1,height:2});const id=s.decorations[0].id;expect(act(s,{type:'placeDecoration',id,location:{kind:'outside',x:23,y:12,rotation:0}},0)).toMatchObject({ok:false,reason:'INVALID_CELL'});s=run(s,{type:'expand',parcelId:'east',expectedCost:500});s=run(s,{type:'placeDecoration',id,location:{kind:'outside',x:23,y:12,rotation:0}});s=run(s,{type:'placeDecoration',id,location:{kind:'outside',x:35,y:12,rotation:1}});expect(decodeGame(encodeGame(s),0)).toEqual({ok:true,state:s})});
 it.each([0,1,2])('converts the historical size %s once preserving resources, ids and jobs',extensions=>{const old=oldSave(extensions);if(extensions)old.buildings.push({...old.buildings[0],id:'building-4',x:3});if(extensions===2)old.buildings.push({...old.buildings[0],id:'building-5',x:6});old.nextId=6;const d=decodeGame(JSON.stringify(old),0);expect(d.ok).toBe(true);if(!d.ok)return;expect(d.state.acquiredParcels).toEqual(extensions===0?['center']:extensions===1?['center','east']:['center','east','west']);expect(d.state.buildings.map(b=>[b.x,b.y])).toEqual(extensions===0?[[12,12]]:extensions===1?[[12,12],[24,12]]:[[12,12],[24,12],[0,12]]);expect([d.state.pattes,d.state.grass,d.state.hearts,d.state.nextId]).toEqual([old.pattes,old.grass,old.hearts,old.nextId]);expect(d.state.rabbits).toEqual(old.rabbits);expect(d.state.missions).toEqual(old.missions);expect(decodeGame(encodeGame(d.state),0)).toEqual({ok:true,state:d.state})});
 it('stores every old interior and discontinuous boundary crossing without changing ids or resources',()=>{const old=oldSave(2);old.buildings.push({...old.buildings[0],id:'building-4',x:1});old.nextId=10;old.decorations=[{id:'decoration-5',catalogId:'soft-cushion',location:{kind:'habitat',habitatId:'building-1',slot:0}},{id:'decoration-6',catalogId:'ball-toys',location:{kind:'habitat',habitatId:'building-1',slot:1}},{id:'decoration-7',catalogId:'play-tunnel',location:{kind:'habitat',habitatId:'building-1',slot:2}},{id:'decoration-8',catalogId:'small-parasol',location:{kind:'habitat',habitatId:'building-4',slot:0}},{id:'decoration-9',catalogId:'wood-bench',location:{kind:'outside',x:23,y:5,rotation:0}}];const json=JSON.stringify(old),values=new Map([[SAVE_KEY,json]]),storage={getItem:(k:string)=>values.get(k)??null,setItem:(k:string,v:string)=>{values.set(k,v)}};const c=new GameController(storage,()=>0),s=c.getSnapshot().state!;expect(s).not.toBeNull();expect(c.getSnapshot().storedDecorations).toBe(5);expect(s.decorations.map(d=>d.id)).toEqual(old.decorations.map(d=>d.id));expect(s.decorations.every(d=>d.location.kind==='inventory')).toBe(true);expect(s.pattes).toBe(old.pattes);expect(s.hearts).toBe(old.hearts);expect(values.get(LAND_MIGRATION_BACKUP_KEY)).toBe(json);const reload=new GameController(storage,()=>0);expect(reload.getSnapshot().storedDecorations).toBe(0);expect(reload.getSnapshot().state).toEqual(s);c.dispose();reload.dispose()});
 it('keeps the v5 raw save if its migration cannot be saved',()=>{const raw=JSON.stringify(oldSave());const values=new Map([[SAVE_KEY,raw]]);const c=new GameController({getItem:k=>values.get(k)??null,setItem:()=>{throw Error('quota')}},()=>0);expect(c.getSnapshot().status).toBe('write-error');expect(values.get(SAVE_KEY)).toBe(raw);expect(c.migrationBackup()).toBe(raw);c.dispose()});
});
